# vars/defaults.yml
# modify for each deployment
---
user_name: admin
sys_packages:
  [
    "nginx",
    "curl",
    "wget",
    "vim",
    "git",
    "tree",
    "ufw",
    "whois",
    "python3-virtualenv",
    "python3-pip",
    "python3-dev",
    "libpq-dev",
  ]
project_repo: "https://github.com/toddgl/FairSystemProject"
app_name: fairsystem-app
django_project_name: fairsystem_proj
ansible_python_interpreter: /usr/local/bin/python3
gnuicorn_port: 8000
projdir: "/home/{{ user_name }}/bin/fairsystem_proj"
etcdir: "/etc/local/fairsystem/"
app_dir: "/home/{{ user_name }}/{{ app_name }}"
django_secret_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
server_IP: XXX.XXX.XXX.XX
fixture_path: /home/user/{{ app_dir }}/{{ app_name}}/fixtures/
django_superuser: admin
django_superuser_password: "{{ django_superuser_password }}"
domain_name: martinboroughfair.org.nz
email: convener@martinboroughfair.org.nz
