---
# tasks file for git
- name: Clone django project respository
  ansible.builtin.git:
    repo: "{{ project_repo }}"
    dest: "{{ projdir }}"
    force: true
    version: master

- name: Recursively change ownership of the cloned directory
  ansible.builtin.file:
    path: "{{ projdir }}/fairsystem"
    state: directory
    recurse: yes
    owner: admin
    group: admin
    mode: "0775"
