---
# tasks file for git
- name: Pull from django project respository
  ansible.builtin.git:
    repo: "{{ project_repo }}"
    dest: "{{ projdir }}"
    clone: False
    update: True
    force: True

- name: Recursively change ownership of the pulled directory
  ansible.builtin.file:
    path: "{{ projdir }}/fairsystem"
    state: directory
    recurse: yes
    owner: admin
    group: admin
    mode: "0775"


