---
- name: Install core web components
  hosts: vultr
  gather_facts: false
  become: true
  remote_user: admin # Should be the same as bootstrap_username

  roles:
    - role: freebsd_certbot_nginx
      tags: [freebsd_certbot_nginx]
