---
- name: Install core web components
  hosts: vultr
  gather_facts: false
  become: true
  vars_files:
    - vars/defaults.yml
  roles:
    - role: app
      tags: [app]
    - role: nginx
      tags: [ngnix]
    - role: postgresql
      tags: [postgresql]
    - role: gunicorn
      tags: [gunicorn]
