---
- name: 
  hosts: vultr
  become: true
  vars_files:
    - secrets.yml
  vars:
    bootstrap_username: admin
    ansible_ssh_pass: "{{ root_passwd }}"

  tasks:
    - name: Karearea SSH key
      ansible.posix.authorized_key:
        user: "{{ bootstrap_username }}"
        state: present
        key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/kr_id_ed25519.pub') }}"
