# test-connection.yml
---
- name: Test Connection and Basic Tasks
  hosts: vultr
  become: yes
  vars_files:
    - secrets.yml
  vars:
    ansible_ssh_pass: "{{ root_passwd }}"

  tasks:
    - name: Ping the target host
      ping:

    - name: Check hostname
      command: hostname
