---
# defaults file for postgresql
postgresql_extra_packages: []
postgresql_conf_dir: "{% if ansible_os_family == 'Debian' %}/etc/postgresql/{{ postgresql_major_version }}/main{% else %}{{ postgresql_db_dir }}{% endif %}"
postgresql_conf_file: "{{ postgresql_conf_dir }}/postgresql.conf"
postgresql_config: ""
postgresql_pg_hba_conf_file: "{{ postgresql_conf_dir }}/pg_hba.conf"
postgresql_pg_hba_config: ""
postgresql_flags: ""
postgresql_initdb_flags: "--encoding=utf-8 --lc-collate=C --locale=en_NZ.UTF-8"
postgresql_debug: "false"
postgresql_initial_password: ""
postgresql_initial_password_file: "{{ postgresql_home_dir }}/.pw"
postgresql_default_login_user: "{{ postgresql_user }}"
postgresql_default_login_password: "{{ postgresql_initial_password }}"
postgresql_default_login_host: 127.0.0.1
postgresql_users: [
"admin"
]
postgresql_databases: [
"fairsystem_db"
]
postgresql_initdb_env: {}
