---
# tasks file for base
- name: Update FreeBSD pkg repository
  become: true
  community.general.pkgng:
    name: "*"
    state: latest

- name: Install base packages
  community.general.pkgng:
    name: "{{ item }}"
  with_items:
    - "{{ sys_packages }}"
