---
- name: Clone django project respository
  ansible.builtin.git:
    repo: "{{ project_repo }}"
    dest: "{{ projdir }}"
    version: master

- name: Copy .env file
  ansible.builtin.template:
    src: production.py
    dest: "{{ projdir }}/.env"
    mode: "666"

- name: Create virtualenv and run pip3 install -r requirement.freeze
  ansible.builtin.pip:
    virtualenv: "{{ projdir }}/venv"
    requirements: "{{ projdir }}/requirements.txt"

- name: Run makemigrations
  community.general.django_manage:
    command: makemigrations
    app_path: "{{ projdir }}"
    settings: "config.settings.base"
    virtualenv: "{{ projdir }}/venv"

- name: Run migrate
  community.general.django_manage:
    command: migrate
    app_path: "{{ projdir }}"
    settings: "config.settings.base"
    virtualenv: "{{ projdir }}/venv"

- name: Run collectstatic
  community.general.django_manage:
    command: collectstatic
    app_path: "{{ projdir }}"
    settings: "config.settings.base"
    virtualenv: "{{ projdir }}/venv"
