---
- name: Clone django project respository
  ansible.builtin.git:
    repo: "{{ project_repo }}"
    dest: "{{ projdir }}"
    force: true
    version: master

- name: Copy .env file
  ansible.builtin.template:
    src: production.py
    dest: "{{ projdir }}/.env"
    mode: "666"

- name: Create virtualenv and run pip3 install -r requirement.freeze
  ansible.builtin.pip:
    virtualenv: "{{ projdir }}/venv"
    requirements: "{{ projdir }}/requirements.txt"

- name: Run makemigrations
  ansible.builtin.command:
    cmd: "{{ projdir }}/venv/bin/python3 {{ projdir }}/manage.py makemigrations --settings=config.settings"

- name: Run migrate
  ansible.builtin.command:
    cmd: "{{ projdir }}/venv/bin/python3 {{ projdir }}/manage.py migrate --settings=config.settings"

- name: Run collectstatic
  ansible.builtin.command:
    cmd: "{{ projdir }}/venv/bin/python3 {{ projdir }}/manage.py collectstatic --settings=config.settings"
