---
- name: create a vultr server
  vultr.cloud.instance:
    api_key: 7UY3YIMJZZMDOHVBPUHME6FFF4UEJOB4OBOA
    name: "{{ vultr_server_name }}" 
    hostname: "{{ vultr_server_name }}"
    os: FreeBSD 13 x64
    plan: vc2-1c-1gb
    region: "{{ vultr_region }}"
    state: started
  register: output

- name: print out ipv4 address
  debug:
    msg: " {{ output.vultr_instance.main_ip }}"

- name: "add {{ vultr_server_name }} to inventory group {{ vultr_inventory_group }}"
  lineinfile:
    path: "{{ inventory_file }}"
    insertafter: "{{ vultr_inventory_group }}"
    line: "{{ vultr_server_name }} ansible_host={{ output.vultr_instance.main_ip }}"

