---
- name: Create a vultr server
  vultr.cloud.instance:
    api_key: "{{ vultr_api_key }}"
    label: "{{ vultr_server_name }}"
    hostname: "{{ vultr_server_name }}"
    os: FreeBSD 13 x64
    plan: vc2-1c-1gb
    ddos_protection: false
    backups: false
    enable_ipv6: true
    region: "{{ vultr_region }}"
    state: started
  register: output

- name: Print out ipv4 address
  ansible.builtin.debug:
    msg: " {{ output.vultr_instance.main_ip }}"

- name: Add server name to inventory group
  ansible.builtin.lineinfile:
    path: "{{ inventory_file }}"
    insertafter: "{{ vultr_inventory_group }}"
    line: "{{ vultr_server_name }} ansible_host={{ output.vultr_instance.main_ip }} ansible_ssh_private_key_file=/home/glenn/.ssh/ansible_id_ed25519"
