---
- name: Delete vultr server
  vultr.cloud.instance:
    api_key: "{{ vultr_api_key }}"
    name: "{{ vultr_server_name }}"
    region: "{{ vultr_region }}"
    state: absent

- name: Remove all instances of vultr server from inventory
  ansible.builtin.lineinfile:
    path: "{{ inventory_file }}"
    regexp: "^{{ vultr_server_name }}"
    state: absent
