---
- include_tasks: create-vultr-server.yml
  when:
    - vultr_server_name is defined
    - vultr_server_name != ""
    - vultr_server_name|length > 0
    - vultr_server_name not in groups[vultr_inventory_group]
    - not delete
 
- include_tasks: delete-vultr-server.yml
  when:
    - vultr_server_name is defined
    - vultr_server_name != ""
    - vultr_server_name|length > 0
    - delete|bool
 
- debug:
    msg: Please enter a value for vultr_server_name variable
  when: vultr_server_name == ""
 
- debug:
    msg: "{{ vultr_server_name }} already exists in group vultr_inventory_group"
  when: 
    - vultr_server_name in groups[vultr_inventory_group]
    - not delete

