---
- name: Create main dirs for {{ etcdir }}
  ansible.builtin.file:
    path: "{{ etcdir }}/{{ app_name }}"
    state: directory
    mode: "755"
- name: Ensure gunicorn is installed.
  community.general.pkgng:
    name: "{{ gunicorn_package_name }}"
    state: present
- name: Copy gunicorn configs
  ansible.builtin.template:
    src: gunicorn_conf.py
    dest: "{{ etcdir }}/{{ app_name }}/gunicorn_conf.py"
    mode: "755"
- name: Copy gunicorn environment file
  ansible.builtin.template:
    src: gunicorn.env
    dest: "{{ etcdir }}/{{ app_name }}/gunicorn.env"
    mode: "755"
