---
# tasks file for nginx
- name: Define nginx_user.
  ansible.builtin.set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined
- name: Update pkg cache.
  command: pkg update -f
  environment:
    ASSUME_ALWAYS_YES: "yes"
  tags: ["skip_ansible_lint"]
- name: Ensure nginx is installed.
  community.general.pkgng:
    name: "{{ nginx_package_name }}"
    state: present
- name: Copy the Nginx configuration file to the host
  ansible.builtin.template:
    src: templates/nginx.j2
    dest: /usr/local/etc/nginx/nginx.conf
    mode: "755"
- name: Create logs directory.
  ansible.builtin.file:
    path: /var/log/nginx
    state: directory
    mode: "600"

- name: Create servers directory directory.
  ansible.builtin.file:
    path: /usr/local/etc/nginx/servers
    state: directory
    mode: "755"

- name: Copy the server definition file to the host
  ansible.builtin.template:
    src: templates/nginx.j2
    dest: /usr/local/etc/servers/mbfairsystem.conf
    mode: "755"
