---
- name: Create main dirs for {{etcdir}}
  file:
    path: "{{etcdir}}"
    state: directory

- name: Copy gunicorn configs
  template:
    src: gunicorn.conf.py
    dest: "{{etcdir}}/gunicorn.conf.py"

- name: Copy gunicorn environment file
  template:
    src: gunicorn.env
    dest: "{{etcdir}}/gunicorn.env"

