---
- name: clone django project respository
  git:
    repo: "{{ project_repo }}"
    dest: "{{ projdir }}"
    version: master
    become_user: {{ user_name  }}

- name: Install production.py
  template:
    src: production.py
    dest: "{{ projdir }}/config/settings/production.py"
    become_user: {{ user_name  }}

- name: Create virtualenv and run pip3 install -r requirement.freeze
  pip:
    virtualenv: "/home/glenn/bin/fairsystemproject/venv"
    requirements: "{{ projdir }}/bin/python3 -m venv"

- name: Run makemigrations
  django_manage:
    command: makemigrations
    app_path: "{{projdir}}"
    settings: "config.settings.production"
    virtualenv: "{{projdir}}/venv"
    become_user: {{ user_name  }}

- name: Run migrate
  django_manage:
    command: migrate
    app_path: "{{projdir}}"
    settings: "config.settings.production"
    virtualenv: "{{projdir}}/venv"
    become_user: {{ user_name  }}

- name: Run collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{projdir}}"
    settings: "config.settings.production"
    virtualenv: "{{projdir}}/venv"
    become_user: {{ user_name  }}


