---
# tasks file for ansible-role-postgresql
- name: Install/upgrade
  ansible.builtin.include_tasks: "install-FreeBSD.yml"

- name: "See if postgresql db_dir exists"
  ansible.builtin.stat:
    path: "{{ deploy_postgresql_db_dir }}"
  register: __stat_postgresql_db_dir

- name: Create initial password file
  ansible.builtin.copy:
    content: "{{ deploy_postgresql_initial_password }}"
    dest: "{{ deploy_postgresql_initial_password_file }}"
    owner: "{{ deploy_postgresql_user }}"
    group: "{{ deploy_postgresql_group }}"
    mode: "0600"
  when:
    - "(not __stat_postgresql_db_dir.stat or not __stat_postgresql_db_dir.stat.exists)"

- name: Include initdb-FreeBSD.yml
  ansible.builtin.include_tasks: initdb-FreeBSD.yml
  when:
    - "(not __stat_postgresql_db_dir.stat or not __stat_postgresql_db_dir.stat.exists)"

- name: Remove postgresql_initial_password_file
  ansible.builtin.file:
    path: "{{ deploy_postgresql_initial_password_file }}"
    state: absent

- name: Create postgresql.conf
  ansible.builtin.template:
    src: postgresql.conf.j2
    dest: "{{ deploy_postgresql_conf_file }}"
    mode: "0600"
  notify: Restart postgresql

- name: Create pg_hba.conf
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: "{{ deploy_postgresql_pg_hba_conf_file }}"
    mode: "0600"
  notify: Restart postgresql

- name: Start postgresql
  ansible.builtin.service:
    name: "{{ deploy_postgresql_service }}"
    state: started

- name: Configure database
  ansible.builtin.include_tasks: "database-setup.yml"
