---
# tasks file for sshd
- name: Copy over sshd_server_config
  ansible.builtin.copy:
    src: sshd_server_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: wheel
    mode: '644'
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    enabled: true
    state: restarted
